### ISSUE TITLE
Add 'url' key Block Definitions.

### ISSUE THREAD

**Issue by matthewhudson** [webpipes/registry.webpipes.org#1]
Without the URL in the definitions, the enduser doesn't know how to call a Block. This pretty much renders this registry useless.

Not sure if we should include a 'url' or 'endpoint' key to the WebPipe Specification, or if there should be a 'meta' key in the registry which then maps to the url/endpoint key. 

At the moment, I'm leaning toward the 'meta' key solution because I can't think of a decent reason for including a 'url' key in the specification.  However, Tom mentioned a 'url' key recently so I thought I'd open it up discussion.

Thoughts?

**Comment by progrium** [comment]
The idea was the registry knows the URL (since it got there) and can store
that separately from the block spec. But it might be convenient to include
the url in the spec. I don't think meta makes sense without something to
specify something more specific. Meta attributes in HTML have keys and
values.

And Joel will tell you: "No meta."

On Thu, Dec 6, 2012 at 11:51 AM, Matthew Hudson notifications@github.comwrote:

> Without the URL in the definitions, the enduser doesn't know how to call a
> Block. This pretty much renders this registry useless.
> 
> Not sure if we should include a 'url' or 'endpoint' key to the WebPipe
> Specification, or if there should be a 'meta' key in the registry which
> then maps to the url/endpoint key.
> 
> At the moment, I'm leaning toward the 'meta' key solution because I can't
> think of a decent reason for including a 'url' key in the specification.
> However, Tom mentioned a 'url' key recently so I thought I'd open it up
> discussion.
> 
> Thoughts?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/webpipes/registry.webpipes.org/issues/1.

## 

Jeff Lindsay
http://progrium.com
